### ISSUE TITLE
Include

### ISSUE THREAD

**Issue by olehkhalin** [foo-software/ghost-graphql#5]
Hey there!

Thank u for your work it is helpful for us now.
Could u tell me please if there any opportunity to use `include` arg?
For example, if I need to get the author and the tag of the post.

**Comment by adamhenson** [comment]
Hi @olehkhalin - you're welcome. yes, this is supported. You could use an introspection tool or even [Apollo Server's GraphQL Playground](https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/) to visualize the schema... or directly in [the source](https://github.com/foo-software/ghost-graphql/blob/master/packages/ghost-graphql/schema.graphql#L22).

You could do something like this:

```gql
posts(include: ["authors", "tags"]) {
  edges {
    node {
      authors {
        name
      }
      html
      primaryTag {
        name
      }
      tags {
        name
      }
      title
    }
  }
}
```

**Comment by adamhenson** [comment]
I'm closing for now, but feel free to comment here or re-open if you're still having an issue. I think the docs could be improved, so eventually I'll get to that. In the meantime, hopefully the schema will provide a sufficient source of truth.

**Comment by olehkhalin** [comment]
We have just set up a server from dockerhub foosoftware/ghost-graphql-server and there is no such functionality. Could u please rebuild and update this container on dockerhub?

**Comment by adamhenson** [comment]
Hi @olehkhalin - thanks for bringing this to my attention. This is a somewhat new feature and I neglected publish the latest image.

I've published a new image to the `latest` tag.

I also opened #6 for better documentation and #7 to add a Docker build to CI.

**Comment by olehkhalin** [comment]
Thanks, it works nice now)
Adam, you have made a cool project, thank you a lot for that

However, one more request, could u add the field `featured` and availability to query only featured posts?

**Comment by adamhenson** [comment]
Hi @olehkhalin - thank you. The idea is that GraphQL inputs and responses mirror Ghost's Content API.

You can utilize the `filter` parameter to get featured posts, similar to the [Content API](https://ghost.org/docs/content-api/#filter).

```gql
posts(include: ["authors", "tags"], filter: ["featured:true"]) {
  edges {
    node {
      authors {
        name
      }
      html
      primaryTag {
        name
      }
      tags {
        name
      }
      title
    }
  }
}
```

I realize this may not be obvious from visualizing the [schema](https://github.com/foo-software/ghost-graphql/blob/master/packages/ghost-graphql/schema.graphql#L22), so this would definitely be a good contender to provide an example for in #6.

Does that answer your question @olehkhalin? I didn't understand the "availability" part of that, so let me know if it doesn't.
